import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir, readFile } from 'node:fs/promises';
const base = 'http://127.0.0.1:4173';
await mkdir('test-results', { recursive: true });
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const errors = [];
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
page.on('pageerror', error => errors.push(error.message));
await page.goto(base); await page.waitForFunction(() => document.querySelectorAll('.winner-card').length === 11);
await page.evaluate(() => document.fonts.ready);
assert.equal(await page.locator('.grid-president .winner-card').count(), 1);
assert.equal(await page.locator('.grid-grand .winner-card').count(), 2);
assert.equal(await page.locator('.grid-excellence .winner-card').count(), 3);
assert.equal(await page.locator('.grid-merit .winner-card').count(), 5);
assert.equal(await page.locator('[data-demo]').isVisible(), true);
assert.equal(await page.evaluate(() => scrollY), 0);
assert.equal(await page.locator('.hero-video-opening').evaluate(v => v.paused), true);
assert.equal(await page.locator('.hero-video-ambient').evaluate(v => v.paused), true);
await page.screenshot({ path: 'test-results/home-desktop.png' });
for (const card of await page.locator('.winner-card').all()) { await card.scrollIntoViewIfNeeded(); }
await page.waitForFunction(() => [...document.querySelectorAll('.card-visual img')].every(i => i.complete && i.naturalWidth > 0));
await page.evaluate(() => window.scrollTo(0, 0));
await page.screenshot({ path: 'test-results/home-full.png', fullPage: true });
await page.locator('.featured-card .card-open').click();
await page.waitForSelector('dialog[open] iframe');
assert.match(await page.locator('dialog iframe').getAttribute('src'), /sample-work.pdf/);
await page.keyboard.press('Escape'); assert.equal(await page.locator('dialog').isVisible(), false);
assert.equal(await page.evaluate(() => document.activeElement.className), 'card-open');
console.log('PASS gallery and PDF');
await page.goto(`${base}/archive.html`); await page.waitForFunction(() => document.querySelectorAll('.winner-card').length === 11);
await page.locator('[data-award=grand]').click(); assert.equal(await page.locator('.winner-card').count(), 2);
await page.locator('[data-award=all]').click(); await page.locator('#search').fill('샘플 연구팀 02');
assert.equal(await page.locator('.winner-card').count(), 1);
await page.reload(); await page.waitForFunction(() => document.querySelectorAll('.winner-card').length === 1);
await page.locator('#search').fill('존재하지않는검색어'); assert.equal(await page.locator('.winner-card').count(), 0);
await page.getByRole('button', { name: '검색 초기화' }).click(); assert.equal(await page.locator('.winner-card').count(), 11);
await page.screenshot({ path: 'test-results/archive-desktop.png' });

const demo = JSON.parse(await readFile('assets/data/demo.json', 'utf8'));
await page.route('**/assets/data/demo.json', route => route.fulfill({ status: 503, body: 'Unavailable' }));
await page.goto(base + '/archive.html'); await page.getByRole('button', { name: '다시 불러오기' }).waitFor();
assert.equal(await page.locator('.winner-card').count(), 0);
await page.unroute('**/assets/data/demo.json'); await page.getByRole('button', { name: '다시 불러오기' }).click();
await page.waitForFunction(() => document.querySelectorAll('.winner-card').length === 11);
await page.route('**/assets/data/demo.json', route => route.fulfill({ json: { ok: true, winners: [{ ...demo.winners[0], title: '<img src=x onerror=alert(1)>', pdfUrl: '', profileUrl: 'https://invalid.example/profile.png' }] } }));
await page.goto(base + '/archive.html'); await page.locator('.winner-card').waitFor();
assert.equal(await page.locator('.card-title img').count(), 0);
await page.waitForFunction(() => document.querySelector('.card-visual img').src.endsWith('profile-placeholder.svg'));
await page.locator('.card-open').click(); await page.getByText('작품 공개를 준비하고 있습니다', { exact: true }).waitFor();
assert.equal(await page.locator('dialog iframe').count(), 0); await page.keyboard.press('Escape');
await page.unroute('**/assets/data/demo.json');
await page.route('**/assets/js/config.js', route => route.fulfill({ contentType: 'text/javascript', body: "export const CONFIG={apiUrl:'',demoMode:false,edition:2026,requestTimeout:1000,autoScrollAfterIntro:true};" }));
await page.goto(base); await page.getByText('수상작 포스터 공개를 준비하고 있습니다').waitFor();
assert.equal(await page.locator('[data-demo]').isVisible(), false);
await page.unroute('**/assets/js/config.js');
console.log('PASS filters, failures and production states');
for (const width of [390, 768, 1440]) {
  await page.setViewportSize({ width, height: 900 });
  for (const name of ['index', 'archive', 'about']) {
    await page.goto(`${base}/${name}.html`);
    if (name !== 'about') await page.waitForFunction(() => document.querySelectorAll('.winner-card').length === 11);
    const fits = await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth);
    assert.equal(fits, true, `${name} overflows at ${width}`);
    if (width === 390) await page.screenshot({ path: `test-results/${name}-mobile.png` });
    if (name === 'about' && width === 1440) await page.screenshot({ path: 'test-results/about-desktop.png', fullPage: true });
  }
}
console.log('PASS responsive layouts');
// Opening film once, then an actual native loop; only the opening can auto-scroll.
const motion = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
await motion.goto(base);
await motion.waitForFunction(() => document.querySelector('.hero-video-opening').currentTime > .5);
assert.match(await motion.locator('.hero-video-opening').getAttribute('src'), /opening-film.mp4/);
assert.equal(await motion.locator('.hero-video-opening').evaluate(v => v.loop), false);
await motion.screenshot({ path: 'test-results/opening-film-desktop.png' });
await motion.waitForFunction(() => document.querySelector('.hero-video-opening').ended, null, { timeout: 15000 });
console.log('PASS video ended');
await motion.waitForFunction(() => document.querySelector('.hero').classList.contains('ambient-visible'));
assert.equal(await motion.locator('.hero-video-ambient').evaluate(v => v.loop && !v.paused), true);
await motion.waitForTimeout(1200);
assert.ok(await motion.evaluate(() => scrollY > 500));
console.log('PASS auto-scroll');
await motion.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }));
await motion.locator('.hero-video-ambient').evaluate(v => { v.currentTime = v.duration - .25; });
await motion.waitForFunction(() => document.querySelector('.hero-video-ambient').currentTime < 2);
assert.equal(await motion.evaluate(() => scrollY), 0);
await motion.screenshot({ path: 'test-results/ambient-loop-desktop.png' });
await motion.locator('[data-replay]').click(); assert.equal(await motion.locator('.hero-video-ambient').evaluate(v => v.paused), true);
await motion.locator('[data-replay]').click(); await motion.waitForFunction(() => !document.querySelector('.hero-video-ambient').paused);
console.log('PASS ambient looping and playback controls');
await motion.goto(base + '/index.html?test=interaction'); await motion.evaluate(() => window.scrollTo(0, 0)); await motion.mouse.click(25, 30); await motion.waitForFunction(() => document.querySelector('.hero-video').ended, { timeout: 15000 });
assert.equal(await motion.evaluate(() => scrollY), 0);
await motion.route('**/opening-film.mp4', route => route.abort());
await motion.goto(base + '/index.html?test=opening-error');
await motion.waitForFunction(() => document.querySelector('.hero').classList.contains('ambient-visible'));
assert.equal(await motion.evaluate(() => scrollY), 0);
await motion.unroute('**/opening-film.mp4');
assert.deepEqual(errors, []);
console.log('PASS: 11 awards, filtering, URL restore, PDF modal and focus, retry, missing PDF, broken image, safe text, production empty state, responsive layouts, video completion and scroll consent.');
await browser.close();
