import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const demo=JSON.parse(await readFile('assets/data/demo.json','utf8'));
const participants=Array.from({length:302},(_,i)=>({...demo.winners[0],id:`p-${i}`,name:`참가팀 ${i+1}`,title:`연구 PART${String(i+1).padStart(3,'0')}`,award:'미수상',order:i+1}));
const rows=[...demo.winners,...participants,{...participants[0],id:'future',year:2027}];
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const base=process.env.TEST_BASE_URL||'http://127.0.0.1:4173';
await page.route('https://script.google.com/macros/s/**',r=>r.fulfill({json:{ok:true,winners:rows}}));
const pager=page.locator('[data-pagination]');
try {
  await page.goto(base+'/archive.html');
  await page.waitForFunction(()=>document.querySelectorAll('.winner-card').length===12);
  assert.match(await page.locator('[data-count]').textContent(),/314/);
  assert.equal(await pager.getByRole('button',{name:'이전 페이지',exact:true}).isDisabled(),true);
  await pager.getByRole('button',{name:'다음 페이지',exact:true}).click();
  assert.match(page.url(),/page=2/);
  assert.equal(await page.locator('.winner-card').count(),12);
  assert.equal(await page.locator('.card-title').first().textContent(),'연구 PART001');
  assert.equal(await page.evaluate(()=>document.activeElement.hasAttribute('data-archive')),true);
  await page.locator('.card-open').first().click();
  await page.waitForSelector('dialog[open] iframe');
  assert.equal(await page.locator('#pdf-title').textContent(),'연구 PART001');
  await page.keyboard.press('Escape');
  await page.reload();await pager.getByRole('button',{name:'2페이지',exact:true}).waitFor();
  assert.equal(await pager.locator('[aria-current=page]').textContent(),'2');
  await pager.getByRole('button',{name:'다음 페이지',exact:true}).click();
  await page.goBack();
  await page.waitForFunction(()=>document.querySelector('.page-status')?.textContent==='2 / 27 페이지');
  await page.goForward();
  await page.waitForFunction(()=>document.querySelector('.page-status')?.textContent==='3 / 27 페이지');
  await pager.getByRole('button',{name:'27페이지',exact:true}).click();
  assert.equal(await page.locator('.winner-card').count(),2);
  assert.equal(await pager.getByRole('button',{name:'다음 페이지',exact:true}).isDisabled(),true);
  await page.getByRole('button',{name:'참가작',exact:true}).click();
  assert.equal(await pager.locator('[aria-current=page]').textContent(),'1');
  assert.doesNotMatch(page.url(),/page=/);
  await pager.getByRole('button',{name:'다음 페이지',exact:true}).click();
  await page.locator('#search').fill('PART025');
  assert.equal(await page.locator('.winner-card').count(),1);assert.equal(await pager.isVisible(),false);
  await page.locator('#search').fill('없는포스터');
  assert.equal(await page.locator('.winner-card').count(),0);assert.equal(await pager.isVisible(),false);
  await page.getByRole('button',{name:'검색 초기화'}).click();
  await pager.getByRole('button',{name:'다음 페이지',exact:true}).click();
  await page.locator('#year').selectOption('2027');
  assert.equal(await page.locator('.winner-card').count(),1);assert.equal(await pager.isVisible(),false);
  await page.goto(base+'/archive.html?page=999');
  await page.waitForFunction(()=>document.querySelectorAll('.winner-card').length===2);
  assert.match(page.url(),/page=27/);
  await page.setViewportSize({width:320,height:850});
  await page.goto(base+'/archive.html?page=14');
  await page.waitForFunction(()=>document.querySelectorAll('.winner-card').length===12);
  await pager.scrollIntoViewIfNeeded();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  assert.equal(await pager.locator('button').count(),7);
  await pager.screenshot({path:'test-results/pagination-mobile.png'});
  for(let n=1;n<=12;n++) {
    const svg=await readFile(`assets/images/sample-${String(n).padStart(2,'0')}.svg`,'utf8');
    assert.doesNotMatch(svg,/<text\b[^>]*>\d+<\/text>/);
  }
  assert.deepEqual(errors,[]);
  console.log('PASS: 314 entries, 12 per page, final page, search/award/year resets, URL/history, PDF, compact mobile pager and unnumbered profiles.');
} finally {await browser.close();}
