import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const base = process.env.TEST_BASE_URL || 'http://127.0.0.1:4173';
const demo = JSON.parse(await readFile('assets/data/demo.json', 'utf8'));
const participant = {...demo.winners[0], id:'participant-public', name:'공개 참가팀', title:'미수상 연구 포스터', award:'미수상'};
let rows = [...demo.winners, participant, {...participant, id:'hidden', name:'숨긴 참가팀', published:false}];
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const errors=[]; page.on('pageerror',e=>errors.push(e.message));
await page.route('https://script.google.com/macros/s/**',r=>r.fulfill({json:{ok:true,winners:rows}}));
try {
  await page.goto(base+'/index.html');
  await page.waitForFunction(()=>document.querySelectorAll('.winner-card').length===11);
  assert.equal(await page.getByText(participant.name,{exact:true}).count(),0);
  assert.equal(await page.locator('[data-demo]').isVisible(),false);
  await page.goto(base+'/archive.html');
  await page.waitForFunction(()=>document.querySelectorAll('.winner-card').length===12);
  assert.equal(await page.getByText('숨긴 참가팀',{exact:true}).count(),0);
  await page.getByRole('button',{name:'참가작',exact:true}).click();
  assert.equal(await page.locator('.winner-card').count(),1);
  assert.equal(await page.locator('.card-meta>span:first-child').textContent(),'참가작');
  await page.reload();
  await page.waitForFunction(()=>document.querySelectorAll('.winner-card').length===1);
  await page.locator('.card-open').click();
  await page.waitForSelector('dialog[open] iframe');
  assert.match(await page.locator('dialog iframe').getAttribute('src'),/sample-work.pdf/);
  await page.keyboard.press('Escape');
  await page.locator('#search').fill('없는 작품');
  assert.equal(await page.locator('.winner-card').count(),0);
  await page.locator('#search').fill('미수상 연구');
  assert.equal(await page.locator('.winner-card').count(),1);
  await page.setViewportSize({width:320,height:850});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:'test-results/participants-mobile.png'});
  rows=[participant];
  await page.goto(base+'/index.html');
  await page.getByText('수상작 포스터 공개를 준비하고 있습니다',{exact:true}).waitFor();
  assert.equal(await page.locator('.winner-card').count(),0);
  assert.equal(await page.locator('[data-demo]').isVisible(),false);
  await page.goto(base+'/archive.html');
  await page.waitForFunction(()=>document.querySelectorAll('.winner-card').length===1);
  assert.equal(await page.locator('.card-meta>span:first-child').textContent(),'참가작');
  assert.deepEqual(errors,[]);
  console.log('PASS mixed/participants-only data, main exclusion, privacy, archive filter/search/reload, PDF and 320px layout.');
} finally {await browser.close();}
